# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(max_length=255, verbose_name='Complemento')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('reference_point', models.CharField(max_length=255, verbose_name='Ponto de Referência')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('country', models.CharField(max_length=255, verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1, verbose_name='Sexo')),
                ('marital_status', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Seprado'), ('VIUVO', 'Viuvo'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10, verbose_name='Estado Cívil')),
                ('birth_date', models.DateField(verbose_name='Data Nascimento')),
                ('cro', models.CharField(max_length=6, verbose_name='CRO')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.Dentist'),
        ),
    ]
