# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1)),
                ('estado_civil', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Seprado'), ('VIUVO', 'Viuvo'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10)),
                ('data_nascimento', models.DateField()),
                ('cro', models.CharField(max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(blank=True, max_length=30)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
