# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='types',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Professor', 'Professor'), ('Técnico Administrativo', 'Técnico Administrativo'), ('Terceirizado', 'Terceirizado'), ('Dependente', 'Dependente')], default='Estudante', max_length=25, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='patientdentalprocedure',
            name='patient_tooth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dental_procedure', to='odontology.PatientTooth'),
        ),
    ]
