# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('odontology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='dentist',
        ),
        migrations.RemoveField(
            model_name='address',
            name='patient',
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='types',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Funcionário', 'Funcionário')], default='Estudante', max_length=20, verbose_name='Tipo'),
        ),
    ]
