# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.Patient')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.Tooth')),
                ('tooth_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ToothStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
