# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='uf',
        ),
        migrations.AddField(
            model_name='dentist',
            name='birth',
            field=models.DateField(default=None, verbose_name='Data Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentist',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='marital_status',
            field=models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Seprado'), ('VIUVO', 'Viuvo'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10, verbose_name='Estado Cívil'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentist',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='cro',
            field=models.CharField(max_length=6, verbose_name='CRO'),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
