# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0002_odontogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('procedure_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ProcedureStatus')),
                ('tooth_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ToothDivision')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
