# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0002_auto_20160322_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontology.Consultation'),
        ),
    ]
