# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0002_auto_20160218_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='oralpatientprocedure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oral_patient_procedure', to='odontology.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
