# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0003_auto_20160222_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('attendance', models.BooleanField()),
                ('oral_patient_procedure', models.ManyToManyField(related_name='consultation_oral_patient_procedure', to='odontology.OralPatientProcedure')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_patient', to='odontology.Patient')),
                ('patient_dental_procedure', models.ManyToManyField(related_name='consultation_patient_dental_procedure', to='odontology.PatientDentalProcedure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
