# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0003_exams_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationSolicitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('appraisal', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontology.Consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='appraisal',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='consultation',
        ),
        migrations.AddField(
            model_name='examinationsolicitation',
            name='exams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontology.Exams'),
        ),
    ]
