# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0003_patientdentalprocedure_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdentalprocedure',
            name='evaluation',
            field=models.BooleanField(default=False),
        ),
    ]
