# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
