# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0004_auto_20160608_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdentalprocedure',
            options={'ordering': ['-created_on'], 'verbose_name': 'Procedimento Dental', 'verbose_name_plural': 'Procedimentos Dental'},
        ),
    ]
