# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0005_consultation_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='oral_patient_procedure',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient_dental_procedure',
        ),
    ]
