# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0005_auto_20160121_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='types',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Funcionário', 'Funcionário'), ('dependente', 'dependente')], default='Estudante', max_length=20, verbose_name='Tipo'),
        ),
    ]
