# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0005_remove_consultation_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
    ]
