# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0006_auto_20160317_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oralpatientprocedure',
            name='patient',
        ),
        migrations.AddField(
            model_name='oralpatientprocedure',
            name='consultation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='odontology.Consultation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdentalprocedure',
            name='consultation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='odontology.Consultation'),
            preserve_default=False,
        ),
    ]
