# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0007_auto_20160122_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pai'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Seprado'), ('VIUVO', 'Viuvo'), ('DIVORCIADO', 'Divorciado')], default=None, max_length=10, null=True, verbose_name='Estado Cívil'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mother',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
