# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0007_auto_20160317_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralpatientprocedure',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontology.Consultation'),
        ),
        migrations.AlterField(
            model_name='patientdentalprocedure',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontology.Consultation'),
        ),
    ]
