# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0009_auto_20160122_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odontogram',
            new_name='PatientTooth',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Este campo é obrigatório', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='marital_status',
            field=models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('SEPARADO', 'Separado'), ('VIUVO', 'Viúvo'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10, verbose_name='Estado Cívil'),
        ),
    ]
