# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0010_auto_20160127_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientDentalProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.Dentist')),
                ('patient_tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.PatientTooth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedureDental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='procedure_status',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='tooth_division',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.AddField(
            model_name='patientdentalprocedure',
            name='procedure_dental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ProcedureDental'),
        ),
        migrations.AddField(
            model_name='patientdentalprocedure',
            name='procedure_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ProcedureStatus'),
        ),
        migrations.AddField(
            model_name='patientdentalprocedure',
            name='tooth_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ToothDivision'),
        ),
    ]
