# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontology', '0011_auto_20160128_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralPatientProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.Dentist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='oralprocedure',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='proceduredental',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='procedurestatus',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='oralpatientprocedure',
            name='oral_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.OralProcedure'),
        ),
        migrations.AddField(
            model_name='oralpatientprocedure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.Patient'),
        ),
        migrations.AddField(
            model_name='oralpatientprocedure',
            name='procedure_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontology.ProcedureStatus'),
        ),
    ]
